Add CloudSQL User accounts for two new independent microservices storing data on the same instance.
Fails because POST sql/Users is apparently serial but unenforced by DM's DAG.
Clients must add explicit dependsOn between potentially unrelated Resource:Users.

ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1547246729294-57f3673adf0b4-1ea48ac4-88eeee89]: errors:
- code: RESOURCE_ERROR
  location: /deployments/db/resources/svc3_user
  message: '{"ResourceType":"sqladmin.v1beta4.user","ResourceErrorCode":"409","ResourceErrorMessage":{"code":409,"errors":[{"domain":"global","message":"Operation
    failed because another operation was already in progress.","reason":"operationInProgress"}],"message":"Operation
    failed because another operation was already in progress.","statusMessage":"Conflict","requestPath":"https://www.googleapis.com/sql/v1beta4/projects/chockstone-dev-hien/instances/dbbox/users","httpMethod":"POST"}}'