Try to delete Resource:User and negligently leave Action:Update in file.
DM catches this due to explicit dependsOn:
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1547171022318-57f24d33129b3-d398f6f1-85afd00e]: errors:
- code: CONDITION_NOT_MET
  message: Referenced resource svc1_user could not be found. At resource rotate_password-svc1_user.