Remove use of Reference between Action:Update and Resource:User. Resort to just hard-coding the username.
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1547169989833-57f2495a6b129-d72fcea1-074d495e]: errors:
- code: RESOURCE_ERROR
  location: /deployments/db/resources/rotate_password-svc1_user
  message: '{"ResourceType":"gcp-types/sqladmin-v1beta4:sql.users.update","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"errors":[{"domain":"global","message":"Invalid
    request: Host required for MySQL instances.","reason":"invalid"}],"message":"Invalid
    request: Host required for MySQL instances.","statusMessage":"Bad Request","requestPath":"https://www.googleapis.com/sql/v1beta4/projects/chockstone-dev-hien/instances/dbbox/users","httpMethod":"PUT"}}'