Create credentials for svc2 using previous pattern that accidentally omits explicit dependsOn.
ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1547171600903-57f24f5adab59-9f14ccee-22f737f3]: errors:
- code: RESOURCE_ERROR
  location: /deployments/db/resources/rotate_password-svc2_user
  message: '{"ResourceType":"gcp-types/sqladmin-v1beta4:sql.users.update","ResourceErrorCode":"409","ResourceErrorMessage":{"code":409,"errors":[{"domain":"global","message":"Operation
    failed because another operation was already in progress.","reason":"operationInProgress"}],"message":"Operation
    failed because another operation was already in progress.","statusMessage":"Conflict","requestPath":"https://www.googleapis.com/sql/v1beta4/projects/chockstone-dev-hien/instances/dbbox/users","httpMethod":"PUT"}}'